-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.usuarios
(
    email text NOT NULL,
    nome text NOT NULL,
    telefone integer NOT NULL,
    senha text NOT NULL,
    PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.candidatos
(
    id serial NOT NULL,
    usuarios_email text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.votacao
(
    id serial NOT NULL,
    data_hora_criacao timestamp without time zone NOT NULL,
    data_hora_fim timestamp without time zone NOT NULL,
    descricao text NOT NULL,
    titulo text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.voto
(
    id serial NOT NULL,
    candidato_id integer NOT NULL,
    usuarios_email text NOT NULL,
    votacao_id integer NOT NULL,
    PRIMARY KEY (votacao_id)
);

CREATE TABLE IF NOT EXISTS public.votacao_candidatos
(
    votacao_id serial NOT NULL,
    candidatos_id serial NOT NULL
);

ALTER TABLE IF EXISTS public.candidatos
    ADD FOREIGN KEY (usuarios_email)
    REFERENCES public.usuarios (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.voto
    ADD FOREIGN KEY (usuarios_email)
    REFERENCES public.usuarios (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.voto
    ADD FOREIGN KEY (votacao_id)
    REFERENCES public.votacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.voto
    ADD FOREIGN KEY (candidato_id)
    REFERENCES public.candidatos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.votacao_candidatos
    ADD FOREIGN KEY (votacao_id)
    REFERENCES public.votacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.votacao_candidatos
    ADD FOREIGN KEY (candidatos_id)
    REFERENCES public.candidatos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;